Basic implementation of `bands.x`
aiidateam/aiida-quantumespresso pull request #1033
Opened 2024-06-15 15:49 UTC by bastonero

An implementation that wraps the binary `bands.x` was missing. This program is used to find the symmetries of wavefunctions, to re-order the bands, and to perform basic post-processings, such as the calculation of the momentum operator.

The current parser only performs basic parsing, with no specialized outputs for k-point wavefunction symmetries, nor momentum operator, nor bands. This can be, for instance, implemented over time depending on user request.

2024-06-18 12:12 UTC, sphuber requested changes
Thanks @bastonero all looks good. Just some minor requests.

As a side note, not sure if you are already aware of `aiida-shell` but for it makes it really easy to run these small kind of utilities without having to write dedicated plugins. You can see [an example of QE the with use of `bands.x`](https://aiida-shell.readthedocs.io/en/latest/examples/qe.html#id6) in the online docs.

2024-06-18 12:12 UTC, sphuber commented on src/aiida_quantumespresso/calculations/bands.py
> +"""`CalcJob` implementation for the q2r.x code of Quantum ESPRESSO."""
```suggestion
"""`CalcJob` implementation for the bands.x code of Quantum ESPRESSO."""
```

2024-06-18 12:12 UTC, sphuber commented on src/aiida_quantumespresso/calculations/bands.py
> +        ('BANDS', 'filband', _BANDS_NAME),  # pylint: disable=protected-access
I think this rule is not used, right?
```suggestion
        ('BANDS', 'filband', _BANDS_NAME),
```

2024-06-18 12:12 UTC, sphuber commented on tests/parsers/fixtures/bands/default/aiida.out
Can you please cut this output to the bare minimum? Just whatever is needed for the parsing to work

2024-06-18 14:18 UTC, bastonero commented on src/aiida_quantumespresso/calculations/bands.py
> +        ('BANDS', 'filband', _BANDS_NAME),  # pylint: disable=protected-access
Right, thanks!

2024-06-18 14:18 UTC, bastonero commented on tests/parsers/fixtures/bands/default/aiida.out
Sure

2024-06-18 14:34 UTC, bastonero commented
Thanks a lot @sphuber for the review.

I was aware of the plugin, but thanks for the reminder, I wasn't aware of the very nice docs. Here I was interested to use the CalcJob/WorkChain for future composite WorkChains. But good to keep in mind about aiida-shell.

2024-06-18 14:35 UTC, bastonero commented
PS: any idea why the docs is always failing lately?

2024-06-20 11:08 UTC, mbercx commented
> PS: any idea why the docs is always failing lately?


Hmm, let me have a look 👀

2024-07-10 11:15 UTC, sphuber approved these changes

2024-07-10 11:22 UTC, sphuber commented
Fixed the RTD build so merging this. Thanks @bastonero

2024-07-10 11:23 UTC, merged