Possibility to run a NamelistCalculation using symlinks to the parent_folder
aiidateam/aiida-quantumespresso pull request #555
Opened 2020-09-18 19:01 UTC by Crivella

In most use-cases, the calculations  that are a subclass of `NamelistCalculation`, are used for post-processing that only reads data from the ./out/ folder of a scf/nscf calculation.

I find it useful to have the option of symlinking the ./out/ folder instead of straight out copying it as it avoids, in some cases, to have to copy 10s to 100s of GB of data, slowing down the starting of the job, and having to clear the remote_data afterwards to avoid huge disk consumption on the cluster.

With this pull request, the option to symlink the ./out/ folder is by default off (to be consistent with older inputs) and is turned on by specifying `'PARENT_FOLDER_SYMLINK': True` in the `settings` input Dict node.

2020-09-19 09:59 UTC, sphuber requested changes
Thanks @Crivella , this looks fine. Could you just please add a quick test?

2020-09-19 23:38 UTC, Crivella commented
@sphuber 
I have added the tests to the pw2gw Calcjob tests (now a parametrized fixture runs the test with and w/o the symlynk option)

2020-09-22 07:40 UTC, sphuber approved these changes

2020-09-22 07:40 UTC, merged

2020-09-22 07:41 UTC, sphuber commented
Thanks a lot @Crivella