`PwBaseWorkChain`: handle diagonalization issues
aiidateam/aiida-quantumespresso pull request #744
Opened 2021-09-22 17:06 UTC by mbercx

Fixes #742 

Add parsing for an error related to the diagonalization, and add a
corresponding exit code to the `PwCalculation`.

Add an error handler to deal with both this exit code as well as the
`ERROR_COMPUTING_CHOLESKY` exit code. In both cases, switching to using
conjugate gradient for the diagonalization seems to be a quite
successful approach for recovering from these failures. If the
calculation was already running conjugate gradient, the
`PwBaseWorkChain` fails with a known unrecoverable failure.

2021-09-22 17:31 UTC, sphuber reviewed
Looks good @mbercx , thanks. Would just at least add a test for the `PwParser` to check the error gets picked up correctly. Bonus points if you add a test for the workchain handler itself, but I think that is less critical

2021-09-22 17:40 UTC, mbercx commented
I've been testing this in the field, and it seems to work quite nicely:

1. Cholesky issues (exit code `462`)
```
PwBaseWorkChain<213713> Finished [0] [5:results]
    ├── create_kpoints_from_distance<213820> Finished [0]
    ├── PwCalculation<213888> Finished [462]
    └── PwCalculation<215363> Finished [0]
PwBaseWorkChain<213899> Finished [0] [5:results]
    ├── create_kpoints_from_distance<213900> Finished [0]
    ├── PwCalculation<213909> Finished [462]
    └── PwCalculation<215765> Finished [0]
...
```

So far I've encountered this error 18 times in my test runs, and _every_ time switching to conjugate gradient seems to fix the problem.

2. "Too many bands not converged" (exit code `463`)
```
PwBaseWorkChain<214832> Finished [0] [5:results]
    ├── create_kpoints_from_distance<215196> Finished [0]
    ├── PwCalculation<215224> Finished [463]
    └── PwCalculation<217771> Finished [0]
PwBaseWorkChain<215379> Finished [0] [5:results]
    ├── create_kpoints_from_distance<215888> Finished [0]
    ├── PwCalculation<215926> Finished [463]
    └── PwCalculation<218431> Finished [0]
...
```

Here it also works most of the time, but there are still some failures. One run already started with `'cg'`, and yet the calculation failed:

```
PwBaseWorkChain<219924> Finished [310] [4:while_(should_run_process)(2:inspect_process)]
    └── PwCalculation<219935> Finished [463]
```

```
$ verdi process report 219924
2021-09-22 17:01:03 [45694 | REPORT]: [219924|PwBaseWorkChain|run_process]: launching PwCalculation<219935> iteration #1
2021-09-22 17:03:55 [45838 | REPORT]: [219924|PwBaseWorkChain|report_error_handled]: PwCalculation<219935> failed with exit status 463: Too many bands failed to converge during the diagonalization.
2021-09-22 17:03:55 [45839 | REPORT]: [219924|PwBaseWorkChain|report_error_handled]: Action taken: found diagonalization issues but already running with conjugate gradient algorithm, aborting...
2021-09-22 17:03:55 [45840 | REPORT]: [219924|PwBaseWorkChain|inspect_process]: PwCalculation<219935> failed but a handler detected an unrecoverable problem, aborting
2021-09-22 17:03:55 [45841 | REPORT]: [219924|PwBaseWorkChain|on_terminated]: remote folders will not be cleaned
```

2021-09-22 17:41 UTC, mbercx commented
> Looks good @mbercx , thanks. Would just at least add a test for the `PwParser` to check the error gets picked up correctly. Bonus points if you add a test for the workchain handler itself, but I think that is less critical

Indeed, still have to fix the tests, on it! Will see how complex it is to get those bonus points. 😎

2021-09-23 07:27 UTC, ramirezfranciscof reviewed
I probably shouldn't be approving this since I never done an error handler before (so I'm more learning how it works by looking at this rather than actually checking if it works), but the general logic looks fine to me.

2021-09-23 09:46 UTC, mbercx commented
> I probably shouldn't be approving this since I never done an error handler before (so I'm more learning how it works by looking at this rather than actually checking if it works), but the general logic looks fine to me.

You can always give it a spin for one of your problematic systems if you'd like. ^^ I've tested it in the field, though, and it seems to work fine! Just going to compare with `ParO` instead of `cg` since that should be much faster [according to Pietro](https://github.com/aiidateam/aiida-quantumespresso/issues/742#issuecomment-925141664).

2021-09-23 10:02 UTC, sphuber commented
> Just going to compare with `ParO` instead of `cg` since that should be much faster [according to Pietro](https://github.com/aiidateam/aiida-quantumespresso/issues/742#issuecomment-925141664).

Note that [ParO wasn't added until QE v6.6](https://github.com/QEF/q-e/releases/tag/qe-6.6), so depending on our new version support protocol we may not yet start to rely on it existing. Making it conditional would be tricky because there is no official way to determine what code version will be used.

2021-09-23 10:22 UTC, mbercx commented
> > Just going to compare with `ParO` instead of `cg` since that should be much faster [according to Pietro](https://github.com/aiidateam/aiida-quantumespresso/issues/742#issuecomment-925141664).
> 
> Note that [ParO wasn't added until QE v6.6](https://github.com/QEF/q-e/releases/tag/qe-6.6), so depending on our new version support protocol we may not yet start to rely on it existing. Making it conditional would be tricky because there is no official way to determine what code version will be used.

Good point! Thanks for looking into this. Re the version of the code: we should really move to adding this to the `Code` somehow. Can we perhaps automatically add the code version to the extras of the `Code` at the start of the parsing?

2021-10-03 18:42 UTC, mbercx commented
@sphuber @ramirezfranciscof since we currently still support all v6.X QE versions, and have no way to determine the version of the code run before parsing, I think we can go ahead and merge this with `'cg'`. It's better to be able to handle this error with a slow method than not handle it at all.

Will open another issue to discuss how we can deal with code version-dependent logic and add a note there that we should update this error handler when we figure this out.

2021-10-03 19:21 UTC, mbercx commented
@sphuber I got the bonus points, but had to comment out the `test_handle_known_unrecoverable_failure` test since we now have no exit codes that need to get handled by this error handler. Not sure if this is fine?

2021-10-04 06:09 UTC, sphuber requested changes
Thanks @mbercx . Couple of small things but should be good to merge after that

2021-10-04 06:09 UTC, sphuber commented on tests/workflows/pw/test_base.py
> +#     assert result == PwBaseWorkChain.exit_codes.ERROR_KNOWN_UNRECOVERABLE_FAILURE
```suggestion
pytest.mark.skip('Reactivate once we have an unrecoverable failure once again.')
 def test_handle_known_unrecoverable_failure(generate_workchain_pw):
     """Test `PwBaseWorkChain.handle_known_unrecoverable_failure`."""
     process = generate_workchain_pw(exit_code=PwCalculation.exit_codes.<INSERT EXIT CODE HERE>)
     process.setup()

     result = process.handle_known_unrecoverable_failure(process.ctx.children[-1])
     assert isinstance(result, ProcessHandlerReport)
     assert result.do_break
     assert result.exit_code == PwBaseWorkChain.exit_codes.ERROR_KNOWN_UNRECOVERABLE_FAILURE

     result = process.inspect_process()
     assert result == PwBaseWorkChain.exit_codes.ERROR_KNOWN_UNRECOVERABLE_FAILURE
```

2021-10-04 06:09 UTC, sphuber commented on tests/workflows/pw/test_base.py
>      assert result.do_break
wait, why is this called a second time?

2021-10-04 06:09 UTC, sphuber commented on aiida_quantumespresso/workflows/pw/base.py
> +            print('ELLO')
```suggestion
```

2021-10-04 06:09 UTC, sphuber commented on aiida_quantumespresso/workflows/pw/base.py
> +        print('WAVE')
```suggestion
```

2021-10-06 09:45 UTC, sphuber commented on tests/workflows/pw/test_base.py
>      assert result.do_break
I see, but that means we still have an `ERROR_KNOWN_UNRECOVERABLE_FAILURE` pathway and you don't have to actually skip the test that checks that path, as you do now. Anyway, this path is checked in the test discussed in this comment, so it is ok to leave for now.

2021-10-06 09:55 UTC, sphuber approved these changes

2021-10-06 09:55 UTC, merged