`ProjwfcParser`: refactor code and temp retrieve PDOS files
aiidateam/aiida-quantumespresso pull request #749
Opened 2021-10-03 15:59 UTC by mbercx

Massive refactoring of the `ProjwfcParser` to make the code less entangled
and more readable.

2021-10-03 16:41 UTC, mbercx commented
Note: the Python 3.6 tests fail because `numpy.ArrayLike` requires a numpy version that no longer supports Python3.6. However, since the EOL of Python 3.6 is in a couple months and the PR is meant to go into v4.0.0, I think we can just leave it as is and drop Python 3.6 support before we merge it.

More importantly, the tests succeed for 581bd57  and Python >= 3.7, without touching the tests. I've also run both the old parser and refactored one for the 4 different spin settings, and compared the content of the orbitals and PDOS arrays. So I'm quite confident that the parsing is unaltered.

2021-10-03 16:56 UTC, mbercx commented
@sphuber this PR is both blocked by #747 and on hold because it contains backwards incompatible changes:

- Drop support for pre-v6.5 QE versions.
- Only temporarily retrieve the PDOS files to lighten the repository.

2025-01-24 07:43 UTC, mbercx commented
@Minotakm @t-reents @AndresOrtegaGuerrero I still have to add the Lowdin parsing, but other than that the PR is ready for review. A line-by-line code review might be quite a bit of work, I'm mainly asking you to test the new parser class and see if it still has any issues. E.g. I think you mentioned the parsing for some cases (spinorbit?) was incorrect.

2025-01-24 07:44 UTC, Minotakm commented
Thanks @mbercx  I will give it a spin and see how it goes.

2025-01-24 09:44 UTC, t-reents requested changes
Thanks @mbercx, I went through it and it looks nice! Definitely easier to understand what is going on, compared to the last version.

As you mentioned, there was still an issue, namely the proper parsing of the total DOS #1041. I added the fix as suggestions (let me know if I should open a PR to your branch instead) and quickly tested them.  @AndresOrtegaGuerrero, please have a look as well.

2025-01-24 09:44 UTC, t-reents commented on src/aiida_quantumespresso/parsers/projwfc.py
> +                dos = pdostot_array[:, 1]
In a spin-polarized calculation (`nspin ==2 `, we only parse the spin-up column at the moment). The suggestion is following the logic of the `dos.x` Parser: 

https://github.com/aiidateam/aiida-quantumespresso/blob/c84ef21dbea1109814e9780d1d18e7303fa2fc25/src/aiida_quantumespresso/parsers/dos.py#L51-L69

```suggestion
                pdostot_array = np.atleast_2d(np.genfromtxt(pdostot_file))
                
                dos = []
                dos_names = []
                energy = pdostot_array[:, 0]
                if nspin ==2:
                    dos += [pdostot_array[:, 1]]
                    dos_names += ['dos_spin_up']
                    dos += [pdostot_array[:, 2]]
                    dos_names += ['dos_spin_down']
                else:
                    dos += [pdostot_array[:, 1]]
                    dos_names += ['dos']
```

2025-01-24 09:44 UTC, t-reents commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        return energy, dos, pdos_array
```suggestion
        return energy, dos, dos_names, pdos_array
```

2025-01-24 09:44 UTC, t-reents commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        :return: tuple of three arrays containing the energy grid, the total DOS and the PDOS
```suggestion
        :return: tuple of three arrays containing the energy grid, the total DOS, the labels of the DOS 
        (spin-up and spin-down) and the PDOS
```

2025-01-24 09:44 UTC, t-reents commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        energy, dos, pdos_array = self._parse_pdos_files(retrieved_temporary_folder, nspin, spinorbit, logs)
```suggestion
        energy, dos, dos_names, pdos_array = self._parse_pdos_files(retrieved_temporary_folder, nspin, spinorbit, logs)
```

2025-01-24 09:44 UTC, t-reents commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        dos_out.set_y(dos, 'Dos', 'states/eV')
```suggestion
        dos_out.set_y(dos, dos_names, ['states/eV'] * len(dos_names))
```

2025-01-24 10:43 UTC, mbercx commented
@t-reents thanks a lot for the review! Feel free to add a commit here with your changes. If possible it would be great if:

* We add a commit that tests this issue, probably via a `pytest` data regression. This will adapt the YAML files corresponding to that regression test. The tests will still pass after the file is updated, but hopefully it's clear that the DOS parsing is incorrect.
* We add a second commit that fixes this parsing problem, clearly showing the change in the data regression YAML files.

This PR will then have 4 commits to merge in the end. I think that is the most clear for future developers.

2025-01-27 09:07 UTC, mbercx commented
> Thanks @mbercx I will give it a spin and see how it goes.

Haha, just noticed the beautiful pun here. Stellar work @Minotakm 😂

2025-01-27 10:00 UTC, AndresOrtegaGuerrero commented
thank you @mbercx I will test it once the new commits are merged then :)

2025-01-27 11:34 UTC, mbercx commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        self.out('Dos', dos_node)
I'd be inclined to change this output name to `dos` (all lowercase), but that is technically backwards-incompatible. However, for the spin-polarised case, by fixing the bug we are also adding an extra array to the `XyData` output, so we are already breaking backwards incompatibility in a sense? Of course changing the output link name would also break backwards incompatibility for the non-spin-polarised case.

Thoughts @t-reents @sphuber @Minotakm @AndresOrtegaGuerrero?

2025-01-27 11:35 UTC, mbercx commented on src/aiida_quantumespresso/parsers/projwfc.py
> +            dos_node.set_y(pdostot_array[:, 1], 'Dos', 'states/eV')
Similar comment as above: I'd use lowercase `dos` for the array name here.

2025-01-28 09:06 UTC, AndresOrtegaGuerrero commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        self.out('Dos', dos_node)
How much is the impact on previous calculations , not much right ?

2025-01-29 15:23 UTC, mbercx commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        self.out('Dos', dos_node)
I mean the QEapp will definitely break, since it will look for the `Dos` output, not the `dos` one, I assume. ^^

2025-01-29 16:26 UTC, AndresOrtegaGuerrero commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        self.out('Dos', dos_node)
we can open an issue to add logic for backwards-compatibility

2025-01-30 08:46 UTC, mbercx commented on src/aiida_quantumespresso/parsers/projwfc.py
> +        self.out('Dos', dos_node)
In the end, I think I'll do the inverse: I'll try and preserve backwards compatibility as much as possible, and open an issue to track breaking changes we want to make. I'd also really like to have `PwCalculation.outputs.structure` instead of `PwCalculation.outputs.output_structure` for example. ^^

2025-01-30 09:54 UTC, Minotakm approved these changes
LGTM! :rocket:

2025-01-30 10:01 UTC, merged