PwBaseWorkChain: handle too high npools
aiidateam/aiida-quantumespresso pull request #758
Opened 2021-11-24 15:59 UTC by unkcpz

hi @mbercx , as I mentioned I add a handler for npool too high error. 
The implement is, I simply finish the PwBaseWorkChain and tag exit status to higher than 700 to indicate the 'warnings'.

2021-11-26 11:37 UTC, mbercx requested changes
All good, thanks @unkcpz! I think the approach of catching the error and finishing with a 7xx exit code is a good one, just left some minor nitpicks.

I was curious why the plugin was simply raising an error previously, and it seems that when the exit code was introduced (#444 , QE v6.4.1), QE would not continue running but simply stop the calculation:

https://github.com/greschd/aiida-quantumespresso/blob/59ded336fda6fa0cd087f88579e9d742eb231fed/tests/parsers/fixtures/pw/failed_npools_too_high/aiida.out

If you have an example for the `aiida.out` for a more recent QE version, maybe you could update the file for this test?

2021-11-26 11:37 UTC, mbercx commented on aiida_quantumespresso/workflows/pw/base.py
> +            message='The npools set too high but the calculation still finished.')
```suggestion
            message='The k-point parallelization `npools` is too high but the calculation still finished successfully.')
```

2021-11-26 11:37 UTC, mbercx commented on aiida_quantumespresso/workflows/pw/base.py
> +        action = 'npools set too high for the calculation but the calculation still finished: consider finished.'
```suggestion
        action = 'k-point parallelization `npools` set too high but the calculation still finished: consider finished.'
```

2022-05-17 15:10 UTC, unkcpz commented
hi @mbercx, sorry for not finishing this PR. I think it was after I start using your hyperqueue this issue never appear to me. Moreover, this problem was caused in my calculation that I only have very few kpoints but I used high npools. I changed that in my workflow and also pass by this issue. 

So in this case, I think it makes sence to raise an error for that, since set npools too high will anyway introduce the performance issue. I close this PR for now, happy to reopen it..

2022-05-17 15:10 UTC, closed without merging