`XspectraCalculation`+`XspectraParser`: Add Features for Restarts and Other Updates
aiidateam/aiida-quantumespresso pull request #837
Opened 2022-09-02 15:18 UTC by PNOGillespie

#### Adds features necessary for restarting XSpectra calculations:
* Reserves the save file name (`xanes.sav`) in the `codeinfo` object.
* The code now automatically includes `xanes.sav` in the `local_copy_list` if the parent calculation is an `XspectraCalculation` (taken from the parent folder), thus simplifying the setup for calculation restarts.
#### Other additions included in the PR:
* A new error code for the `XspectraParser` (code 315) to detect if the code has cleanly exited after reaching a set maximum time limit (including an accompanying test).
* A slight increase to the `output_parameters` collected: adds the polarisation vectors chosen for the calculation and whether the calculation was set to re-plot (i.e. `xonly_plot = .true./.false.` in the inputs).
* Support for including an optional `gamma_file` (`SinglefileData` format) required to run calculations using an external file for applying spectral broadening to the final spectrum (using `gamma_mode = "file"`).

2022-09-05 20:03 UTC, sphuber requested changes
Thanks @PNOGillespie . Just some minor comments but overall the changes look good.

2022-09-05 20:03 UTC, sphuber commented on src/aiida_quantumespresso/calculations/xspectra.py
> +        if restart_flag:
Here is a useful shortcut
```suggestion
        parent_folder = self.inputs.parent_folder
        parent_calc = parent_folder.creator

        if parent_calc.process_type == 'aiida.calculations:quantumespresso.xspectra':
```

2022-09-05 20:03 UTC, sphuber commented on src/aiida_quantumespresso/parsers/xspectra.py
> +                return self.exit(self.exit_codes.ERROR_OUTPUT_TIME_LIMIT_EXCEEDED)
```suggestion
                return self.exit(self.exit_codes.ERROR_OUT_OF_WALLTIME)
```

2022-09-05 20:03 UTC, sphuber commented on tests/parsers/fixtures/xspectra/failed_timeout/aiida.out
> +     -------------------------------------------------------------------------
For this test, try to cut out as much of this file as possible while the test still works. You are just testing here that if `Calculation not finished` is found at the bottom, the parser returns the right exit code.

2022-09-05 20:03 UTC, sphuber commented on tests/parsers/test_xspectra.py
> +    assert calcfunction.exit_status == node.process_class.exit_codes.ERROR_OUTPUT_TIME_LIMIT_EXCEEDED.status
```suggestion
    assert calcfunction.exit_status == node.process_class.exit_codes.ERROR_OUT_OF_WALLTIME.status
```

2022-09-12 08:27 UTC, PNOGillespie commented
Thank you @sphuber for the review, I will put out a new commit after my meetings today to shorten the out-of-walltime test file.

Regarding the discussion here: https://github.com/aiidateam/aiida-quantumespresso/pull/837#discussion_r963109005 - The original formulation included FolderData as a means to provide a parent calculation for the calculation run, however the use of this wasn't tested before and I'm not familiar with the procedure for retrieving the files required in order to use the FolderData node properly for this purpose. I have opted to simply remove the option from the inputs for now and then add it back in via a later commit once I understand how this process works.

2022-09-27 07:41 UTC, sphuber commented on src/aiida_quantumespresso/calculations/xspectra.py
> +        spec.input('parent_folder', valid_type=(orm.RemoteData), required=True)
Could you please still clarify this comment? Why is `FolderData` (i.e. restarting from `retrieved` folder) not supported?

2022-09-27 07:42 UTC, sphuber requested changes
Thanks @PNOGillespie . Just one minor mistake in the test docstring and ~~one outstanding comment~~. If you can address those, this can be merged.

Edit: never mind, I see you addressed that comment regarding the `FolderData` in a separate post. Just the docstring then and I will merge this.

2022-09-27 07:42 UTC, sphuber commented on tests/parsers/test_xspectra.py
> +    """Test `XspectraParser` to correctly report error code 315 (time limit exceeded)."""
```suggestion
    """Test ``XspectraParser`` to correctly report ``ERROR_OUT_OF_WALLTIME``."""
```

2022-09-27 07:54 UTC, PNOGillespie commented
Thank you for the reply @sphuber (and for spotting that mistake). I've addressed the requested change, so I'll leave the rest to you.

2022-09-27 08:17 UTC, merged