Having pw schema XML support all valide disk_io options
aiidateam/aiida-quantumespresso pull request #911
Opened 2023-04-12 15:13 UTC by unkcpz

fixes #908

2023-04-12 16:35 UTC, sphuber requested changes

2023-04-12 16:35 UTC, sphuber commented on tests/parsers/fixtures/pw/default_xml_220603/data-file-schema.xml
> +      <disk_io>nowf</disk_io>
As you mentioned in the corresponding issue, this change as a means to test the changes in the schema is perhaps not the best. If we really feel we need to test this, we add a dedicated test that takes an example output XML for each schema version, then parametrizes it over the valid values of `disk_io` and just calls the schema validation. So completely decouple it from the parser tests.

But I am not sure this is even needed as now we are testing the validity of the schema, which should be static. So I think that if you run an example calculation locally with these changes and disk_io set to nowf and it works, then we accept that without specific unit tests.
```suggestion
      <disk_io>low</disk_io>
```

2023-04-12 19:34 UTC, unkcpz commented
Okay, thanks change it back. I test locally and works all good.

2023-04-13 09:55 UTC, bastonero commented
Passing by I'd suggest putting a reminder in the Wiki about this for future scheme releases. And maybe a test with a xml produced with a calculation specifying the ``disc_io`` with one of these options? (probably overtesting though)

2023-04-13 12:12 UTC, merged