WIP: Switch to using MyST Markdown
aiidateam/aiida-quantumespresso pull request #929
Opened 2023-05-05 23:00 UTC by mbercx

2023-05-08 10:26 UTC, sphuber commented
Thanks @mbercx . I'm fine with the move in principle. Just noticed that the styling is quite different in the new build. Is this because some styling rules are not migrated properly yet, or because one of the updated dependencies changes the style? Did `sphinx-book-theme` change the appearance that much? I think I prefer the current style personally

2023-05-09 04:50 UTC, mbercx commented
I think the styling changes are mainly due to the bump in the `sphinx-book-theme` indeed, which was necessary. We can change the defaults for sure, though, just let me know which changes you're not a fan of and I can look into it.

2023-05-09 18:40 UTC, sphuber requested changes
Thanks @mbercx . Let's not get into bikeshedding on the styling. It's more important to get this in so it becomes easier to start adding additional docs. I have one open question though.

2023-05-10 03:45 UTC, mbercx commented on rst2myst.yaml
Well spotted! That one snuck in accidentally indeed. Removed 👍

2023-05-10 05:09 UTC, sphuber approved these changes

2023-05-10 05:13 UTC, merged